### ISSUE TITLE
Invalid shaders when opening with 2017.3.0f3

### ISSUE THREAD

**Issue by citizenmatt** [Zaphyk/project-skylines#24]
If I open the project in Unity 2017.3.0f3, there are shader errors (the dreaded magenta!) for the `Ship0`, `Ship1` and `Terrain` materials. They're all configured to use the `Hidden/InternalErrorShader` shader.

What shader(s) should they be using?

**Comment by Zaphyk** [comment]
This works as expected because the shader is closes source and hasn't been included in the source code. I will add a replacement shader and some warnings later so this doesn't cause confusion.

**Comment by citizenmatt** [comment]
OK. Thanks for the clarification!
