### ISSUE TITLE
how to build it

### ISSUE THREAD

**Issue by punksta** [Zaphyk/project-skylines#5]
Please provide build instructions on different os.

**Comment by Zaphyk** [comment]
Do you mean how to set up the project or how to export different versions?

**Comment by punksta** [comment]
Just how to compile\make executed file

**Comment by Zaphyk** [comment]
You need to clone the repo and open the project using Unity 2017 then just build the project for the versions you want. However there is a couple of missing files so when you build the game the main shader will be missing.
