### ISSUE TITLE
Changing controls on Windows

### ISSUE THREAD

**Issue by PyvesB** [Zaphyk/project-skylines#6]
Hello there,

Congrats for your nomination as one of the winners of Game Off 2017! :wink:

I had a quick play around with the game and seem to be unable to change the default controls. I have modified both _Primary_ and _Secondary_  inputs in the settings, but these changes don't seem to take effect once the game is launched.

Cheers,

Pyves

**Comment by Zaphyk** [comment]
Hey, thanks for reporting the issue.
I fixed it on commit e8391fc36c01191e5c81efd55097e6a8e60e9676 but you will see the changes reflected in the game later today when I push a new build :D

**Comment by PyvesB** [comment]
Awesome, thanks!

**Comment by Zaphyk** [comment]
I released a new version on itch and here on GitHub which fixed this issue. You should try it out. [Neon Skylines 1.1](https://github.com/Zaphyk/project-skylines/releases/tag/v1.1.0)
