### ISSUE TITLE
Wrong result score when it's more than 1000

### ISSUE THREAD

**Issue by LEQADA** [Zaphyk/project-skylines#7]
OS: Ubuntu 16.04

When the score is higher than 1000 and you hit the wall on the result score value the last digit is not displayed.
For example: If you your score is 1053 and you hit the wall the result score will be displayed as 105.

PS:
Congrats on winning the "Best graphics" award, it looks really cool :)

**Comment by Zaphyk** [comment]
Thanks! fixed in 5d027460fc5ab4b8965118e9adcb10f72e56ba4d
