### ISSUE TITLE
Trying to Run Project on Unity 5.4 version

### ISSUE THREAD

**Issue by Pranavpaharia** [Zaphyk/project-skylines#8]
I'm getting error in running the project in Unity 5.4 . 
Error 1:
Assets/Standard Assets/Effects/ImageEffects/Scripts/CameraMotionBlur.cs(77,75): error CS1061: Type `UnityEngine.Camera' does not contain a definition for `GetStereoProjectionMatrix' and no extension method `GetStereoProjectionMatrix' of type `UnityEngine.Camera' could be found (are you missing a using directive or an assembly reference?)

Error2:
EditorOnlyPlayerSettings property UNet_ServiceEnabled::UNet_ServiceEnabled not inititalized. Please initialize it using corresponding PlayerSettings.InitializeProperty function!
UnityEditor.Web.JSProxyMgr:DoTasks()

**Comment by Zaphyk** [comment]
The project version is Unity 2017.2.0f3, try with that.
